export const medicalSpeciality = {
    ro: [
        { value: "100", label: "ACUPUNCTURA" },
        { value: "SP01", label: "ALERGOLOGIE SI IMUNOLOGIE" },
        { value: "101", label: "ALERGOLOGIE SI IMUNOLOGIE CLINICA PEDIATRICA" },
        { value: "SP47", label: "ANATOMIE PATOLOGICA" },
        { value: "100", label: "ANDROLOGIE" },
        { value: "SP02", label: "ANESTEZIE SI TERAPIE INTENSIVA" },
        { value: "SP50", label: "ASISTENT MEDICAL" },
        { value: "SP03", label: "BOLI INFECTIOASE" },
        { value: "SP04", label: "CARDIOLOGIE" },
        { value: "101", label: "CARDIOLOGIE PEDIATRICA" },
        { value: "101", label: "CHIRURGIE BARIATRICA" },
        { value: "SP26", label: "CHIRURGIE CARDIOVASCULARA" },
        { value: "SP27", label: "CHIRURGIE GENERALA" },
        { value: "11", label: "CHIRURGIE HEPATO BILIO PANCREATICA" },
        { value: "SP32", label: "CHIRURGIE ONCOLOGICA" },
        { value: "SP166", label: "CHIRURGIE ORALA SI MAXILO - FACIALA" },
        { value: "SP37", label: "CHIRURGIE ORTOPEDIE PEDIATRICA" },
        { value: "SP29", label: "CHIRURGIE PEDIATRICA" },
        { value: "SP30", label: "CHIRURGIE PLASTICA - MICROCHIRURGIE RECONSTRUCTIVA" },
        { value: "101", label: "CHIRURGIE PROCTOLOGIE" },
        { value: "SP31", label: "CHIRURGIE TORACICA" },
        { value: "SP26", label: "CHIRURGIE VASCULARA" },
        { value: "SP11", label: "CONSILIERE ALAPTARE" },
        { value: "101", label: "CT" },
        { value: "SP05", label: "DERMATOVENEROLOGIE" },
        { value: "SP06", label: "DIABET ZAHARAT, NUTRITIE SI BOLI METABOLICE" },
        { value: "101", label: "DIETETICA" },
        { value: "100", label: "ECOGRAFIE" },
        { value: "101", label: "ECOGRAFIE MORFOFETALA" },
        { value: "101", label: "ELECTROENCEFALOGRAMA" },
        { value: "SP07", label: "ENDOCRINOLOGIE" },
        { value: "101", label: "ENDOCRINOLOGIE PEDIATRICA" },
        { value: "100", label: "ENDOSCOPIE DIGESTIVA" },
        { value: "SP03", label: "EPEMIOLOGIE" },
        { value: "103", label: "FIZIOTERAPIE" },
        { value: "SP08", label: "GASTROENTEROLOGIE" },
        { value: "100", label: "GASTROENTEROLOGIE PEDIATRICA" },
        { value: "ac54", label: "GENETICA MEDICALA" },
        { value: "SP48", label: "GERIATRIE SI GERONTOLOGIE" },
        { value: "SP10", label: "HEMATOLOGIE" },
        { value: "101", label: "HEMATOLOGIE PEDIATRICA" },
        { value: "100", label: "HOMEOPATIE" },
        { value: "103", label: "KINETOTERAPIE" },
        { value: "SL01", label: "LABORATOR" },
        { value: "101", label: "LOGOPEDIE" },
        { value: "101", label: "MAMOGRAFIE" },
        { value: "100", label: "MASAJ" },
        { value: "SP11", label: "MEDICINA DE FAMILIE" },
        { value: "SL01", label: "MEDICINA DE LABORATOR" },
        { value: "SP12", label: "MEDICINA DE URGENTA" },
        { value: "SP48", label: "MEDICINA GENERALA" },
        { value: "SP13", label: "MEDICINA INTERNA" },
        { value: "100", label: "MEDICINA MARITIMA" },
        { value: "101", label: "MEDICINA MATERNO-FETALA" },
        { value: "SP14", label: "MEDICINA MUNCII" },
        { value: "130", label: "MEDICINA MUNCII COMPETENTA" },
        { value: "101", label: "MICOLOGIE" },
        { value: "SP15", label: "NEFROLOGIE" },
        { value: "100", label: "NEFROLOGIE PEDIATRICA" },
        { value: "SP16", label: "NEONATOLOGIE" },
        { value: "SP33", label: "NEUROCHIRURGIE" },
        { value: "SP17", label: "NEUROLOGIE" },
        { value: "100", label: "NEUROLOGIE EMG" },
        { value: "SP18", label: "NEUROLOGIE PEDIATRICA" },
        { value: "SP22", label: "NEUROPSIHIATRIE INFANTILA" },
        { value: "SP34", label: "OBSTETRICA - GINECOLOGIE" },
        { value: "SP35", label: "OFTALMOLOGIE" },
        { value: "100", label: "OFTALMOLOGIE PEDIATRICA" },
        { value: "SP19", label: "ONCOLOGIE MEDICALA" },
        { value: "101", label: "ONCOLOGIE PEDIATRICA" },
        { value: "SP38", label: "ORL (OTORINOLARINGOLOGIE)" },
        { value: "101", label: "ORL PEDIATRIC (OTORINOLARINGOLOGIE)" },
        { value: "SP37", label: "ORTOPEDIE SI TRAUMATOLOGIE" },
        { value: "SP36", label: "ORTOPEDIE SI TRAUMATOLOGIE PEDIATRICA" },
        { value: "103", label: "OSTEODENSITOMETRIE" },
        { value: "SP20", label: "PEDIATRIE" },
        { value: "101", label: "PLANNING FAMILIAL" },
        { value: "SP21", label: "PNEUMOLOGIE" },
        { value: "100", label: "PNEUMOLOGIE PEDIATRICA" },
        { value: "SP22", label: "PSIHIATRIE" },
        { value: "SP22", label: "PSIHIATRIE PEDIATRICA" },
        { value: "SP49", label: "PSIHOLOGIE" },
        { value: "101", label: "PSIHOTERAPIE" },
        { value: "SP40", label: "RADIOLOGIE - IMAGISTICA MEDICALA" },
        { value: "SP175", label: "RADIOTERAPIE" },
        { value: "SP51", label: "RECUPERARE MEDICALA" },
        { value: "SP25", label: "REUMATOLOGIE" },
        { value: "101", label: "REUMATOLOGIE PEDIATRICA" },
        { value: "103", label: "RMN" },
        { value: "130", label: "SOMNOLOGIE" },
        { value: "100", label: "STERILITATE" },
        { value: "103", label: "TEHNICIAN" },
        { value: "SP39", label: "UROLOGIE" },
        { value: "101", label: "UROLOGIE PEDIATRICA" }
    ],
    en: [
        { value: "100", label: "ACUPUNCTURE" },
        { value: "SP01", label: "ALLERGOLOGY AND IMMUNOLOGY" },
        { value: "101", label: "PEDIATRIC CLINICAL ALLERGOLOGY AND IMMUNOLOGY" },
        { value: "SP47", label: "PATHOLOGICAL ANATOMY" },
        { value: "100", label: "ANDROLOGY" },
        { value: "SP02", label: "ANESTHESIA AND INTENSIVE THERAPY" },
        { value: "SP50", label: "MEDICAL ASSISTANT" },
        { value: "SP03", label: "INFECTIOUS DISEASES" },
        { value: "SP04", label: "CARDIOLOGY" },
        { value: "101", label: "PEDIATRIC CARDIOLOGY" },
        { value: "101", label: "BARIATRIC SURGERY" },
        { value: "SP26", label: "CARDIOVASCULAR SURGERY" },
        { value: "SP27", label: "GENERAL SURGERY" },
        { value: "11", label: "PANCREATIC BILIO HEPATO SURGERY" },
        { value: "SP32", label: "ONCOLOGICAL SURGERY" },
        { value: "SP166", label: "ORAL AND MAXILLO - FACIAL SURGERY" },
        { value: "SP37", label: "PEDIATRIC ORTHOPEDIC SURGERY" },
        { value: "SP29", label: "PEDIATRIC SURGERY" },
        { value: "SP30", label: "PLASTIC SURGERY - RECONSTRUCTIVE MICROSURGERY" },
        { value: "101", label: "SURGERY PROCTOLOGY" },
        { value: "SP31", label: "THORACIC SURGERY" },
        { value: "SP26", label: "VASCULAR SURGERY" },
        { value: "SP11", label: "BREASTFEEDING ADVISOR" },
        { value: "101", label: "CT" },
        { value: "SP05", label: "DERMATOVENEROLOGY" },
        { value: "SP06", label: "DIABETES, NUTRITION AND METABOLIC DISEASES" },
        { value: "101", label: "DIETETICS" },
        { value: "100", label: "ULTRASOUND" },
        { value: "101", label: "MORPHOPHETAL ULTRASOUND" },
        { value: "101", label: "ELECTROENCEPHALOGRAM" },
        { value: "SP07", label: "ENDOCRINOLOGY" },
        { value: "101", label: "PEDIATRIC ENDOCRINOLOGY" },
        { value: "100", label: "DIGESTIVE ENDOSCOPY" },
        { value: "SP03", label: "EPEMIOLOGY" },
        { value: "103", label: "PHYSIOTHERAPY" },
        { value: "SP08", label: "GASTROENTEROLOGY" },
        { value: "100", label: "PEDIATRIC GASTROENTEROLOGY" },
        { value: "ac54", label: "MEDICAL GENETICS" },
        { value: "SP48", label: "GERIATRICS AND GERONTOLOGY" },
        { value: "SP10", label: "HEMATOLOGY" },
        { value: "101", label: "PEDIATRIC HEMATOLOGY" },
        { value: "100", label: "HOMEOPATHY" },
        { value: "103", label: "KINETOTHERAPY" },
        { value: "SL01", label: "LABORATOR" },
        { value: "101", label: "LOGOPEDIE" },
        { value: "101", label: "MAMMOGRAPHY" },
        { value: "100", label: "MASSAGE" },
        { value: "SP11", label: "FAMILY MEDICINE" },
        { value: "SL01", label: "LABORATORY MEDICINE" },
        { value: "SP12", label: "EMERGENCY MEDICINE" },
        { value: "SP48", label: "GENERAL MEDICINE" },
        { value: "SP13", label: "INTERNAL MEDICINE" },
        { value: "100", label: "MARITIME MEDICINE" },
        { value: "101", label: "MATERNAL-FETAL MEDICINE" },
        { value: "SP14", label: "OCCUPATIONAL MEDICINE" },
        { value: "130", label: "COMPETENT OCCUPATIONAL MEDICINE" },
        { value: "101", label: "MYCOLOGY" },
        { value: "SP15", label: "NEPHROLOGY" },
        { value: "100", label: "PEDIATRIC NEPHROLOGY" },
        { value: "SP16", label: "NEONATOLOGY" },
        { value: "SP33", label: "NEUROSURGERY" },
        { value: "SP17", label: "NEUROLOGY" },
        { value: "100", label: "EMG NEUROLOGY" },
        { value: "SP18", label: "PEDIATRIC NEUROLOGY" },
        { value: "SP22", label: "CHILD NEUROPSYCHIATRY" },
        { value: "SP34", label: "OBSTETRICA - GINECOLOGIE" },
        { value: "SP35", label: "OPHTHALMOLOGY" },
        { value: "100", label: "PEDIATRIC OPHTHALMOLOGY" },
        { value: "SP19", label: "MEDICAL ONCOLOGY" },
        { value: "101", label: "PEDIATRIC ONCOLOGY" },
        { value: "SP38", label: "ENT (OTORHINOLARYNGOLOGY)" },
        { value: "101", label: "PEDIATRIC ENT (OTORHINOLARYNGOLOGY)" },
        { value: "SP37", label: "ORTHOPEDICS AND TRAUMATOLOGY" },
        { value: "SP36", label: "ORTHOPEDICS AND PEDIATRIC TRAUMATOLOGY" },
        { value: "103", label: "OSTEODENSITOMETRIE" },
        { value: "SP20", label: "PEDIATRICS" },
        { value: "101", label: "FAMILY PLANNING" },
        { value: "SP21", label: "PNEUMOLOGY" },
        { value: "100", label: "PEDIATRIC PNEUMOLOGY" },
        { value: "SP22", label: "PSYCHIATRY" },
        { value: "SP22", label: "PEDIATRIC PSYCHIATRY" },
        { value: "SP49", label: "PSYCHOLOGY" },
        { value: "101", label: "PSYCHOTHERAPY" },
        { value: "SP40", label: "RADIOLOGY - MEDICAL IMAGING" },
        { value: "SP175", label: "RADIOTHERAPY" },
        { value: "SP51", label: "MEDICAL RECOVERY" },
        { value: "SP25", label: "RHEUMATOLOGY" },
        { value: "101", label: "PEDIATRIC RHEUMATOLOGY" },
        { value: "103", label: "NMR" },
        { value: "130", label: "SOMNOLOGY" },
        { value: "100", label: "STERILITY" },
        { value: "103", label: "TECHNICIAN" },
        { value: "SP39", label: "UROLOGY" },
        { value: "101", label: "PEDIATRIC UROLOGY" }
    ]
}